### ISSUE TITLE
libtest

### ISSUE THREAD

**Issue by felixplasser** [libwfa/libwfa#1]
Currently, libwfa can only be compiled when libtest is present. This should be set up in a more flexible way.

**Comment by Jellby** [comment]
Where can I get libtest from, anyway?

**Comment by felixplasser** [comment]
libtest is proprietary code of Q-Chem, unfortunately. This should be replaced with an open-source test library at some point.

What type of applications do you have in mind?

**Comment by Jellby** [comment]
I see, I just wanted to test it with Molcas. Any progress in that front?

**Comment by felixplasser** [comment]
It is looking quite good in fact. But I have not yet had the time to finalize it yet. I will write progress report on the Molcas forum:
https://cobalt.itc.univie.ac.at/molcasforum/viewtopic.php?id=13
Hopefully, I will have time for that today ...
