### ISSUE TITLE
how to visualize NBO, NTO

### ISSUE THREAD

**Issue by wangh0606** [libwfa/libwfa#35]
Do you have more tutorial or manual on libwfa? I would like to know how to visualize the excitation or the average orbitals or NTO, NBO. Basically, I would like to know which electron is excited to which unoccupied orbital. It seems that libwfa write some visualization information to the hdf5 it reads. But pegamoid.py crashes when I tried to visualize it.

**Comment by felixplasser** [comment]
Hi, are you talking about libwfa+Molcas? The documentation for this can be found here:
https://molcas.gitlab.io/OpenMolcas/sphinx/users.guide/programs/wfa.html

At this point there is no interface to pegamoid but it would be a logical thing to have. Right now, you have to use the penny program and run:
`penny molcas.rassi.h5 --wfaorbs molden`
This will produce the NOs, NTOs, and NDOs in Molden format. penny can be found here:
https://github.com/felixplasser/molpy

**Comment by wangh0606** [comment]
Thanks a lot!
I will try penny then.
