### ISSUE TITLE
Error:Did not find any MO-coefficients

### ISSUE THREAD

**Issue by lchaus** [libwfa/libwfa#53]
Hello,
After several successful runs I'm encountering a weird error with the WFA module in Openmolcas which I can't make sense of.

```
()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()

                                                &WFA

                                   only a single process is used
                       available to each process: 75 GB of memory, 1 thread?
                                             pid: 84748
()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()

 Starting wavefunction analysis ...
Parsing input file ...
Opening Molcas HDF5 file molcas.rassi.h5

Did not find any MO-coefficients
 Number of atoms: 43
--- Stop Module: wfa at Wed Jul  5 00:57:38 2023 /rc=-11 ---

.########################.
.# Non-zero return code #.
.########################.
```

The rassi.h5 file seems indeed to contain MO coeffs that I can look at with Pegamoid so I don't really understand this error. It should be noted that it is large (2.5GB). I'm a little confused because I successfully obtained WFA outputs for Theodore similarly with same compiled Openmolcas (23.02  559-gfa600edc0) but slightly smaller systems.

It was generated this way:

```
>>SAVE  $Project.JobMix JOB001
&RASSI
  Nrofjobiphs
  1       11
  1 2 3 4 5 6 7 8 9 10 11
  Heff
  TRD1

&WFA
  h5file = molcas.rassi.h5

```
Any thoughts on this most welcome.

**Comment by felixplasser** [comment]
Hi, I am happy to have a look at it. Always nice to see if people are using WFA.

Can you make your input file or molcas.rassi.h5 available (maybe via something like dropbox or OneDrive)?

**Comment by lchaus** [comment]
Thanks for the quick fix, all good now.
